### ISSUE TITLE
An elements vs Elements typo in composer.json?

### ISSUE THREAD

**Issue by pixelplumber** [SchmidtWebmedia/grid-for-gridelements#3]
Hi.  Not a developer, just an integrator of TYPO3, but trying out your extension in TYPO3 9.5 and I receive errors in the BE re. missing classes eg: "An error occurred trying to process items for field "twocol" (No class named SchmidtWebmedia\GridForGridElements\Controller\GridController)."

Is it because the composer.json line is lower case _elements_ instead of _Elements_?  Doesn't match the namespaces in the Classes folder?

https://github.com/SchmidtWebmedia/grid-for-gridelements/blob/b2527f215d3e09f710d3c2e3c9eb706eef36c30c/composer.json#L25

`$ grep -Rin forgridelement *                                                                                                                                                                                    grep: bin/.ea-php-cli.cache: No such file or directory                                                                                                                                                                                       composer/autoload_psr4.php:75:    'SchmidtWebmedia\\GridForGridelements\\' => array($baseDir . '/public_html/typo3conf/ext/grid_for_gridelements/Classes'),                                                                                  composer/autoload_static.php:191:            'SchmidtWebmedia\\GridForGridelements\\' => 36,                                                                                                                                                 composer/autoload_static.php:564:        'SchmidtWebmedia\\GridForGridelements\\' =>                                                                                                                                                         composer/installed.json:5657:                "SchmidtWebmedia\\GridForGridelements\\": "Classes"       `

The namespaces in the Classes folder all have capital E.

**Comment by pixelplumber** [comment]
If I sed -i 's/GridForGridelements/GridForGridElements/g' on the composer autoload files and installed.json in vendor/composer/ the extension works.
I tried changing the composer.json file included in the extension and clearing the composer cache and updating, but I assume it doesn't work as it pulls the lower case version off the typo3-ter repo?

**Comment by SchmidtWebmedia** [comment]
Sorry for late response. I didn't get any notification about an issue.
Currently I have no instance running on Composer. Maybe you can checkout the current master and tell me if it work now?

**Comment by pixelplumber** [comment]
Hi Marco, no worries at all!  Pulling that from github direct instead of ter that update fixes it for me.
Cheers,
Mark.
