### ISSUE TITLE
Grid For Gidelements renders nothing (TYPO3 10.x, Bootstrap Package 11.x)

### ISSUE THREAD

**Issue by lexwebmaker** [SchmidtWebmedia/grid-for-gridelements#6]
Grid For Gidelements doesn't render anything.

I've followed the steps for a Basic configuration. The Bakend is correct (display are correct), but Fontend is empty.

TYPO3 10.x
Bootstrap Package 11.x
grid_for_gridelements  2.0.0

Can you help?

**Comment by SchmidtWebmedia** [comment]
Hey, 
you need the Extension "GidElements" as a dependency. 
BR

**Comment by lexwebmaker** [comment]
Hello,
 Thanks for your answer.
"gridelements" is automatically installed since it's one of the two dependencies of "grid-for-gridelements" in its ext_emconf and composer files.

And, just in case, YES I did add the static templates as recommended here : https://docs.typo3.org/p/schmidtwebmedia/grid-for-gridelements/1.3/en-us/Configuration/Basic/Index.html 
![static-templates](https://user-images.githubusercontent.com/55317556/87407274-edde8580-c58f-11ea-80ce-6f81a9de77d9.png)

In the Backend, it is correctly rendered
![in-the-backend](https://user-images.githubusercontent.com/55317556/87407480-39912f00-c590-11ea-87b7-30a7ffb2fe58.png)

BUT in the frontend, nothing except from grid-for-gridelements...
![in-the-frontend](https://user-images.githubusercontent.com/55317556/87407749-9260c780-c590-11ea-8260-63f02217abb0.png)

Your extension is a very nice one. Please investigate before closing the issue.

Looking forward to hearing from you

**Comment by SchmidtWebmedia** [comment]
Please add "fluid_styled_content" as static template

**Comment by lexwebmaker** [comment]
Unfortunately, "fluid_styled_content" is in conflicts with "Bootstrap Package", a must-have package to build websites quickly.

Is it possible to solve that?

**Comment by SchmidtWebmedia** [comment]
I have tried to reproduce it. If you add the static template from bootstrap_package it will work. Have you tried it?

**Comment by SchmidtWebmedia** [comment]
Did you tried it? Does it work?

**Comment by lexwebmaker** [comment]
Sorry for the delay. 
I've planned to test today (Montreal time) with a fresh TYPO3 10.4.x with Bootstrap Package and Grid For Elements installed and configured.

I'll keep you updated!

**Comment by SchmidtWebmedia** [comment]
Hey, any news on that?

**Comment by lexwebmaker** [comment]
Hello @SchmidtWebmedia. I found something : the extension [content_animations](https://extensions.typo3.org/extension/content_animations/) is the cause of the problem, once the config for Bootstrap included, GFE stops working.

Let me investigate today before closing this issue!

**Comment by SchmidtWebmedia** [comment]
Hey @lexwebmaker does it work or the issue still exist?

**Comment by lexwebmaker** [comment]
Hello @SchmidtWebmedia. I started investigating but didn't have enough time to finish. So, let's close the issue.

I'll try to communicate with the developer of content_animations when I'll be able to come back to this (may be in tow weeks).

I'll keep you updated if the change to make is on your side.

Thanks for your help!
