### ISSUE TITLE
 TYPO3 v10: Form inside a bootstrap grid is not being rendered.

### ISSUE THREAD

**Issue by tuberlinapp** [SchmidtWebmedia/grid-for-gridelements#7]
I have tested it with TYPO3 v10.4.9 and the form_formframework of TYPO3.
Created a default form, choosed "2 columns" grid and placed it in the first column.
The form inside the grid is not being rendered.
When putting the form element outside of the grid, the form is rendered.

**Comment by SchmidtWebmedia** [comment]
Hey, thanks for your report.
Please take a look at version 2.1.0. This should fix your problem.
