### ISSUE TITLE
Make grid-for-gridelements more compatible with Bootstrap Package 11.x

### ISSUE THREAD

**Issue by lexwebmaker** [SchmidtWebmedia/grid-for-gridelements#9]
It has become now an unwritten convention to use "Main" as section name in Template and Layout Fluid files. The advantage of that is that the extension can easier work with other extensions that must take control of the ContentElement layout (Ex : Bootstrap Package). It is also easier to provide a custom Layout file that is the result of the merge of Layout files of other extensions (Ex : Bootstrap Package + Content Animations + ...) and our own custom HTML/Fluid code.

So I suggest to rename from "**Col**" to "**Main**" in the [Template files](https://github.com/SchmidtWebmedia/grid-for-gridelements/tree/master/Resources/Private/Templates) (and to update the [Layout file](https://github.com/SchmidtWebmedia/grid-for-gridelements/blob/master/Resources/Private/Layouts/Default.html) consequently).

In addition, I suggest to remove from the [Partial file](https://github.com/SchmidtWebmedia/grid-for-gridelements/blob/master/Resources/Private/Partials/Default.html) all the code related to the "frame" and let Bootstrap Package handle that in its Layout file.

**Comment by SchmidtWebmedia** [comment]
I checked your requestes here. One questions: Why should I delete the "frame" classes? I want to use the frame settings in the gridelement to get space between each grid container. Is there another recommended solution for this?

**Comment by lexwebmaker** [comment]
By deleting the "frame" class from the Partial file, you let to the Editor the option to choose whether or not he wants space between each grid container. BootstrapPackage already handles the "space" feature for you. To add space by himself, the Editor will just have to select "Default" (or anything else different from "No Frame") as frame in the Appearance tab of the corresponding content element, BootstrapPackage will wrap the content with the corresponding DIV and frame classes.

With BootstrapPackage you can add "Space Before" and "Space After" too in addition. 

So, it's not necessary to handle that in your extension.

Someone that doesn't have BootstrapPackage can still use CSS to add spaces (by styling grid-* and ge-*).

**Comment by SchmidtWebmedia** [comment]
In order for the editor that he is able to adjust the spacing at all, the classes have to be output somewhere and that is at this point. If I remove them, nothing happens and the "space-before" and "space-after" settings are ignored.

On my local test environment I have installed the bootstrap_package and if I remove the frame classes, nothing happen. I changed already the naming from "Col" to "Main" in the Templates, but there is no difference.

And if a editor does not change the values in the "Appearance tab" no space will added to this containers.

**Comment by SchmidtWebmedia** [comment]
Please check current master if this solve this issue

**Comment by lexwebmaker** [comment]
> 
> 
> Please check current master if this solve this issue

YES. That's exactly what I have on my side and let me tell you that it work like a charme.

Your extension is awesome by the way!

**Comment by SchmidtWebmedia** [comment]
Thanks. I just released the new version 2.2.0
